const express=require('express');
const multer=require('multer');
const XLSX=require('xlsx');
const fs=require('node:fs');
const path=require('node:path');
const {db,root}=require('./db');
const {now,hashPassword,requireAdmin,requireRole,audit}=require('./auth');
const {migrateLocal}=require('./migration');
const {importWorkbook}=require('./excel');
const router=express.Router();
const j=v=>{try{return JSON.parse(v||'{}')}catch{return {}}};
const body=v=>JSON.stringify(v===undefined?{}:v);
const all=(sql,p=[])=>db.prepare(sql).all(...p),one=(sql,p=[])=>db.prepare(sql).get(...p),newId=r=>Number(r.lastInsertRowid);

router.get('/categories',(_q,r)=>r.json({ok:true,data:all('SELECT * FROM categories ORDER BY sort,name')}));
router.post('/categories',requireRole('admin','editor'),(q,r)=>{const b=q.body||{},x=db.prepare('INSERT INTO categories(name,template_schema,sort) VALUES(?,?,?)').run(b.name||'',body(b.templateSchema),b.sort||0);r.status(201).json({ok:true,data:one('SELECT * FROM categories WHERE id=?',[newId(x)])})});
router.put('/categories/:id',requireRole('admin','editor'),(q,r)=>{const b=q.body||{};db.prepare('UPDATE categories SET name=?,template_schema=?,sort=? WHERE id=?').run(b.name||'',body(b.templateSchema),b.sort||0,q.params.id);r.json({ok:true})});
router.delete('/categories/:id',requireRole('admin'),(q,r)=>{db.prepare('DELETE FROM categories WHERE id=?').run(q.params.id);r.json({ok:true})});
router.get('/products',(_q,r)=>r.json({ok:true,data:all('SELECT * FROM products ORDER BY sort,name').map(x=>({...x,specs:j(x.specs)}))}));
router.post('/products',requireRole('admin','editor'),(q,r)=>{const b=q.body||{},x=db.prepare('INSERT INTO products(sku_code,name,category_id,brand,model,finish,unit,price,main_image_url,dimension_draft_url,svg_diagram_url,specs,sort) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(b.skuCode||'',b.name||'',b.categoryId||null,b.brand||'',b.model||'',b.finish||'',b.unit||'',b.price||0,b.mainImageUrl||'',b.dimensionDraftUrl||'',b.svgDiagramUrl||'',body(b.specs),b.sort||0);r.status(201).json({ok:true,data:{id:newId(x)}})});
router.put('/products/:id',requireRole('admin','editor'),(q,r)=>{const b=q.body||{};db.prepare('UPDATE products SET sku_code=?,name=?,category_id=?,brand=?,model=?,finish=?,unit=?,price=?,main_image_url=?,dimension_draft_url=?,svg_diagram_url=?,specs=?,sort=? WHERE id=?').run(b.skuCode||'',b.name||'',b.categoryId||null,b.brand||'',b.model||'',b.finish||'',b.unit||'',b.price||0,b.mainImageUrl||'',b.dimensionDraftUrl||'',b.svgDiagramUrl||'',body(b.specs),b.sort||0,q.params.id);r.json({ok:true})});
router.delete('/products/:id',requireRole('admin'),(q,r)=>{db.prepare('DELETE FROM products WHERE id=?').run(q.params.id);r.json({ok:true})});
router.get('/product-pages',(_q,r)=>r.json({ok:true,data:all('SELECT * FROM product_pages ORDER BY updated_at DESC').map(x=>({...x,page:j(x.page_json),sourceFile:j(x.source_file_json)}))}));
router.post('/product-pages/bulk',requireRole('admin','editor'),(q,r)=>{const pages=q.body?.pages||{},t=now(),upsert=db.prepare('INSERT INTO product_pages(sku_code,page_json,source_file_json,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(sku_code) DO UPDATE SET page_json=excluded.page_json,source_file_json=excluded.source_file_json,updated_at=excluded.updated_at');db.exec('BEGIN');try{for(const [sku,page] of Object.entries(pages))upsert.run(sku,body(page),body(page?.sourceFile),t,t);db.exec('COMMIT');r.json({ok:true,data:{count:Object.keys(pages).length}})}catch(e){db.exec('ROLLBACK');r.status(400).json({ok:false,error:e.message})}});
router.get('/product-pages/:sku',(q,r)=>{const x=one('SELECT * FROM product_pages WHERE sku_code=?',[q.params.sku]);if(!x)return r.status(404).json({ok:false,error:'产品单页不存在'});r.json({ok:true,data:{...x,page:j(x.page_json),sourceFile:j(x.source_file_json)}})});
router.post('/product-pages',requireRole('admin','editor'),(q,r)=>{const b=q.body||{},t=now(),page=b.page||b.pageJson||{};if(!b.skuCode)return r.status(400).json({ok:false,error:'缺少产品型号'});try{const x=db.prepare('INSERT INTO product_pages(product_id,sku_code,page_json,source_file_json,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(b.productId||null,b.skuCode,body(page),body(b.sourceFile),t,t);r.status(201).json({ok:true,data:{id:newId(x),skuCode:b.skuCode}})}catch(e){if(/UNIQUE/i.test(e.message))return r.status(409).json({ok:false,error:'产品型号已存在'});throw e}});
router.put('/product-pages/:sku',requireRole('admin','editor'),(q,r)=>{const b=q.body||{},page=b.page||b.pageJson||{},x=db.prepare('UPDATE product_pages SET product_id=?,page_json=?,source_file_json=?,updated_at=? WHERE sku_code=?').run(b.productId||null,body(page),body(b.sourceFile),now(),q.params.sku);if(!x.changes)return r.status(404).json({ok:false,error:'产品单页不存在'});r.json({ok:true})});
router.delete('/product-pages/:sku',requireRole('admin'),(q,r)=>{db.prepare('DELETE FROM product_pages WHERE sku_code=?').run(q.params.sku);r.json({ok:true})});
// ===== 用户管理（仅 admin）=====
const safeUser=u=>({id:u.id,username:u.username,displayName:u.display_name,role:u.role,status:u.status||(u.is_active?'active':'disabled'),sessionHours:u.session_hours||168,mustChangePassword:!!u.must_change_password,expiresAt:u.expires_at||null,accountDays:u.expires_at?Math.max(0,Math.round((new Date(u.expires_at)-new Date())/86400000)):0,passwordExpiresAt:u.password_expires_at||null,failedLoginCount:u.failed_login_count||0,lockedUntil:u.locked_until||null,lastLoginAt:u.last_login_at||null,createdAt:u.created_at,updatedAt:u.updated_at});
router.get('/users',requireAdmin,(_q,r)=>r.json({ok:true,data:all('SELECT * FROM users ORDER BY id').map(safeUser)}));
router.post('/users',requireAdmin,(q,r)=>{const b=q.body||{};const username=String(b.username||'').trim();const password=String(b.password||'');const displayName=String(b.displayName||username);const role=['admin','editor','viewer'].includes(b.role)?b.role:'viewer';if(!username)return r.status(400).json({ok:false,error:'用户名必填'});if(password.length<6)return r.status(400).json({ok:false,error:'密码至少6位'});const existing=one('SELECT id FROM users WHERE username=?',[username]);if(existing)return r.status(409).json({ok:false,error:'用户名已存在'});const p=hashPassword(password);const sessionHours=Number(b.sessionHours)||168;
const accDays=Number(b.accountDays)||0;
const expAt=accDays>0?new Date(Date.now()+accDays*86400000).toISOString():null;
const x=db.prepare('INSERT INTO users(username,display_name,role,password_hash,password_salt,must_change_password,session_hours,is_active,expires_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(username,displayName,role,p.hash,p.salt,Number(b.mustChangePassword?1:0),sessionHours,1,expAt,now(),now());r.status(201).json({ok:true,data:safeUser(one('SELECT * FROM users WHERE id=?',[newId(x)]))})});
router.put('/users/:id',requireAdmin,(q,r)=>{const b=q.body||{},id=Number(q.params.id);const u=one('SELECT * FROM users WHERE id=?',[id]);if(!u)return r.status(404).json({ok:false,error:'用户不存在'});if(Number(u.id)===1&&b.role&&b.role!=='admin')return r.status(400).json({ok:false,error:'初始管理员不能降级'});let expAt=u.expires_at;
if(b.accountDays!==undefined){const d=Number(b.accountDays)||0;expAt=d>0?new Date(Date.now()+d*86400000).toISOString():null;}
const fields={display_name:b.displayName??u.display_name,role:['admin','editor','viewer'].includes(b.role)?b.role:u.role,session_hours:Number(b.sessionHours)||u.session_hours,is_active:b.isActive==null?u.is_active:(b.isActive?1:0),must_change_password:b.mustChangePassword==null?u.must_change_password:Number(b.mustChangePassword?1:0),expires_at:expAt,updated_at:now()};if(b.password){if(String(b.password).length<6)return r.status(400).json({ok:false,error:'密码至少6位'});const p=hashPassword(String(b.password));db.prepare('UPDATE users SET password_hash=?,password_salt=?,must_change_password=0 WHERE id=?').run(p.hash,p.salt,id);}db.prepare('UPDATE users SET display_name=?,role=?,session_hours=?,is_active=?,must_change_password=?,expires_at=?,updated_at=? WHERE id=?').run(fields.display_name,fields.role,fields.session_hours,fields.is_active,fields.must_change_password,fields.expires_at,fields.updated_at,id);r.json({ok:true,data:safeUser(one('SELECT * FROM users WHERE id=?',[id]))})});
router.delete('/users/:id',requireAdmin,(q,r)=>{const id=Number(q.params.id);if(id===1)return r.status(400).json({ok:false,error:'不能删除初始管理员'});if(req_user_is_self(q,id))return r.status(400).json({ok:false,error:'不能删除自己'});db.prepare('DELETE FROM users WHERE id=?').run(id);r.json({ok:true})});
function req_user_is_self(q,id){return q.user&&q.user.id===id;}
// ===== 全局设置 =====
router.get('/settings',requireAdmin,(_q,r)=>{const rows=all('SELECT key,value FROM settings');const out={};rows.forEach(x=>out[x.key]=x.value);r.json({ok:true,data:out})});
router.put('/settings',requireAdmin,(q,r)=>{const b=q.body||{};const up=db.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');for(const k of Object.keys(b))up.run(k,String(b[k]));r.json({ok:true})});
// audit logs (admin)
router.get('/audit-logs',requireAdmin,(q,r)=>{const limit=Math.min(500,Number(q.query.limit)||200);r.json({ok:true,data:all('SELECT * FROM audit_logs ORDER BY id DESC LIMIT ?',[limit])})});
// list active sessions (admin)
router.get('/sessions',requireAdmin,(_q,r)=>r.json({ok:true,data:all("SELECT s.id,s.user_id,s.device_name,s.ip_address,s.user_agent,s.created_at,s.last_active_at,s.expires_at,s.revoked_at,u.username FROM sessions s JOIN users u ON u.id=s.user_id ORDER BY s.created_at DESC LIMIT 500")}));
router.delete('/sessions/:id',requireAdmin,(q,r)=>{db.prepare('UPDATE sessions SET revoked_at=? WHERE id=?').run(now(),q.params.id);r.json({ok:true})});
router.post('/users/:id/logout-all',requireAdmin,(q,r)=>{db.prepare('UPDATE sessions SET revoked_at=? WHERE user_id=? AND revoked_at IS NULL').run(now(),q.params.id);r.json({ok:true})});
router.get('/case-state',(q,r)=>{const uid=q.user.id;const row=one('SELECT data,updated_at,version FROM case_state WHERE user_id=?',[uid]);if(!row)return r.json({ok:true,data:{data:null}});r.json({ok:true,data:{data:j(row.data),updatedAt:row.updated_at,version:row.version||1}})});
router.put('/case-state',requireRole('admin','editor'),(q,r)=>{const uid=q.user.id;const data=q.body?.data;const clientVersion=Number(q.body?.version)||0;if(data==null)return r.status(400).json({ok:false,error:'缺少数据'});const cur=one('SELECT version FROM case_state WHERE user_id=?',[uid]);const serverVersion=cur?cur.version:0;if(clientVersion>0&&clientVersion!==serverVersion)return r.status(409).json({ok:false,error:'数据已被其他设备修改，请刷新后重试',serverVersion});const t=now();db.prepare('INSERT INTO case_state(user_id,data,updated_at,version) VALUES(?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at,version=excluded.version').run(uid,JSON.stringify(data),t,serverVersion+1);r.json({ok:true,data:{updatedAt:t,version:serverVersion+1}})});
router.get('/product-db',(_q,r)=>{const row=one('SELECT rows,updated_at FROM product_db WHERE id=1');let rows=[];try{rows=row?JSON.parse(row.rows):[]}catch{rows=[]}r.json({ok:true,data:{rows,updatedAt:row?.updated_at||null,version:row?.version||1}})});
router.put('/product-db',requireRole('admin','editor'),(q,r)=>{const rows=Array.isArray(q.body?.rows)?q.body.rows:[];const clientVersion=Number(q.body?.version)||0;const cur=one('SELECT version FROM product_db WHERE id=1');const serverVersion=cur?cur.version:0;if(clientVersion>0&&clientVersion!==serverVersion)return res.status(409).json({ok:false,error:'数据已被其他设备修改，请刷新后重试',serverVersion});const t=now();db.prepare('INSERT INTO product_db(id,rows,updated_at,version) VALUES(1,?,?,?) ON CONFLICT(id) DO UPDATE SET rows=excluded.rows,updated_at=excluded.updated_at,version=excluded.version').run(JSON.stringify(rows),t,serverVersion+1);r.json({ok:true,data:{count:rows.length,updatedAt:t,version:serverVersion+1}})});
router.get('/projects',(_q,r)=>r.json({ok:true,data:all('SELECT * FROM projects ORDER BY updated_at DESC').map(x=>({...x,settings:j(x.settings)}))}));
router.get('/state',(q,r)=>{const project=one('SELECT * FROM projects WHERE id=?',[q.query.projectId||0]);if(!project)return r.status(404).json({ok:false,error:'项目不存在'});const products=all('SELECT * FROM products ORDER BY sort,name').map(x=>({...x,specs:j(x.specs)})),sets=all('SELECT * FROM hardware_sets ORDER BY set_code').map(s=>({...s,items:all('SELECT i.*,p.sku_code,p.name,p.finish,p.unit,p.brand FROM hardware_set_items i JOIN products p ON p.id=i.product_id WHERE i.set_id=?',[s.id])}));r.json({ok:true,data:{project:{...project,settings:j(project.settings)},products,sets,doors:all('SELECT * FROM door_schedules WHERE project_id=? ORDER BY seq,id',[project.id]),productPages:all('SELECT * FROM product_pages ORDER BY updated_at DESC').map(x=>({...x,page:j(x.page_json),sourceFile:j(x.source_file_json)}))}})});
router.post('/projects',requireRole('admin','editor','project_manager'),(q,r)=>{const b=q.body||{},t=now(),x=db.prepare('INSERT INTO projects(name,plan_code,settings,created_at,updated_at) VALUES(?,?,?,?,?)').run(b.name||'未命名项目',b.planCode||'',body(b.settings),t,t);r.status(201).json({ok:true,data:{id:newId(x)}})});
router.put('/projects/:id',requireRole('admin','editor','project_manager'),(q,r)=>{const b=q.body||{};db.prepare('UPDATE projects SET name=?,plan_code=?,settings=?,updated_at=? WHERE id=?').run(b.name||'',b.planCode||'',body(b.settings),now(),q.params.id);r.json({ok:true})});
router.delete('/projects/:id',requireRole('admin'),(q,r)=>{db.prepare('DELETE FROM projects WHERE id=?').run(q.params.id);db.prepare('DELETE FROM door_schedules WHERE project_id=?').run(q.params.id);r.json({ok:true})});
router.get('/projects/:id/versions',(q,r)=>r.json({ok:true,data:all('SELECT * FROM project_versions WHERE project_id=? ORDER BY created_at DESC',[q.params.id]).map(x=>({...x,snapshot:j(x.snapshot)}))}));
router.post('/projects/:id/versions',(q,r)=>{const b=q.body||{},x=db.prepare('INSERT INTO project_versions(project_id,name,snapshot,created_at) VALUES(?,?,?,?)').run(q.params.id,b.name||'未命名版本',body(b.snapshot),now());r.status(201).json({ok:true,data:{id:newId(x)}})});
router.delete('/projects/:id/versions/:vid',(q,r)=>{db.prepare('DELETE FROM project_versions WHERE id=? AND project_id=?').run(q.params.vid,q.params.id);r.json({ok:true})});
router.get('/sets',(_q,r)=>r.json({ok:true,data:all('SELECT * FROM hardware_sets ORDER BY set_code')}));
router.get('/sets/detail',(q,r)=>r.json({ok:true,data:all('SELECT s.*,i.id item_id,i.product_id,i.quantity_per_door,i.remark FROM hardware_sets s LEFT JOIN hardware_set_items i ON i.set_id=s.id ORDER BY s.set_code')}));
router.post('/sets',(q,r)=>{const b=q.body||{},x=db.prepare('INSERT INTO hardware_sets(set_code,name,material,door_type,fire_rating,remark) VALUES(?,?,?,?,?,?)').run(b.setCode||'',b.name||'',b.material||'',b.doorType||'',b.fireRating||'',b.remark||'');r.status(201).json({ok:true,data:{id:newId(x)}})});
router.put('/sets/:id',(q,r)=>{const b=q.body||{};db.prepare('UPDATE hardware_sets SET set_code=?,name=?,material=?,door_type=?,fire_rating=?,remark=? WHERE id=?').run(b.setCode||'',b.name||'',b.material||'',b.doorType||'',b.fireRating||'',b.remark||'',q.params.id);r.json({ok:true})});
router.delete('/sets/:id',(q,r)=>{db.prepare('DELETE FROM hardware_set_items WHERE set_id=?').run(q.params.id);db.prepare('DELETE FROM hardware_sets WHERE id=?').run(q.params.id);r.json({ok:true})});
router.post('/sets/:id/items',(q,r)=>{const b=q.body||{},x=db.prepare('INSERT INTO hardware_set_items(set_id,product_id,quantity_per_door,remark) VALUES(?,?,?,?)').run(q.params.id,b.productId,b.quantityPerDoor||1,b.remark||'');r.status(201).json({ok:true,data:{id:newId(x)}})});
router.put('/sets/:id/items/:itemId',(q,r)=>{const b=q.body||{},x=db.prepare('UPDATE hardware_set_items SET product_id=?,quantity_per_door=?,remark=? WHERE id=? AND set_id=?').run(b.productId,b.quantityPerDoor||1,b.remark||'',q.params.itemId,q.params.id);if(!x.changes)return r.status(404).json({ok:false,error:'五金组明细不存在'});r.json({ok:true})});
router.delete('/sets/:id/items/:itemId',(q,r)=>{db.prepare('DELETE FROM hardware_set_items WHERE id=? AND set_id=?').run(q.params.itemId,q.params.id);r.json({ok:true})});
router.get('/doors',(q,r)=>r.json({ok:true,data:all('SELECT * FROM door_schedules WHERE project_id=? ORDER BY seq,id',[q.query.projectId||0])}));
router.post('/doors',(q,r)=>{const list=Array.isArray(q.body)?q.body:(q.body?.doors||[]),projectId=q.body?.projectId||q.query.projectId||0,ins=db.prepare('INSERT INTO door_schedules(project_id,seq,floor,door_number,door_model,room_function,width,height,thickness,qty,material,fire_rating,door_type,set_id,section,remark) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');db.exec('BEGIN');try{const ids=list.map((b,i)=>newId(ins.run(b.projectId||projectId,b.seq??i,b.floor||'',b.doorNumber||'',b.doorModel||'',b.roomFunction||'',b.width??null,b.height??null,b.thickness??null,b.qty||1,b.material||'',b.fireRating||'',b.doorType||'',b.setId||null,b.section||'',b.remark||'')));db.exec('COMMIT');r.status(201).json({ok:true,data:ids})}catch(e){db.exec('ROLLBACK');r.status(400).json({ok:false,error:e.message})}});
router.put('/doors/:id',(q,r)=>{const b=q.body||{};db.prepare('UPDATE door_schedules SET floor=?,door_number=?,door_model=?,room_function=?,width=?,height=?,thickness=?,qty=?,material=?,fire_rating=?,door_type=?,set_id=?,section=?,remark=? WHERE id=?').run(b.floor||'',b.doorNumber||'',b.doorModel||'',b.roomFunction||'',b.width??null,b.height??null,b.thickness??null,b.qty||1,b.material||'',b.fireRating||'',b.doorType||'',b.setId||null,b.section||'',b.remark||'',q.params.id);r.json({ok:true})});
router.delete('/doors/:id',(q,r)=>{db.prepare('DELETE FROM door_schedules WHERE id=?').run(q.params.id);r.json({ok:true})});
router.post('/doors/bulk-set',(q,r)=>{const ids=q.body?.ids||[],x=db.prepare('UPDATE door_schedules SET set_id=? WHERE id=?');ids.forEach(i=>x.run(q.body.setId||null,i));r.json({ok:true,count:ids.length})});
router.get('/bom',(q,r)=>r.json({ok:true,data:all('SELECT p.sku_code,p.name,p.unit,p.price,SUM(COALESCE(d.qty,1)*i.quantity_per_door) total_quantity,SUM(COALESCE(d.qty,1)*i.quantity_per_door)*p.price total_price FROM door_schedules d JOIN hardware_set_items i ON i.set_id=d.set_id JOIN products p ON p.id=i.product_id WHERE d.project_id=? GROUP BY p.id',[q.query.projectId||0])}));
const upload=multer({storage:multer.diskStorage({destination:path.join(root,'public/uploads'),filename:(_q,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^\w.\-一-龥]/g,'_'))}),limits:{fileSize:5*1024*1024},fileFilter:(_q,f,cb)=>cb(null,/^image\/(png|jpeg|webp)$/.test(f.mimetype))});
const importUpload=multer({dest:path.join(root,'data'),limits:{fileSize:20*1024*1024}});
const documentUpload=multer({storage:multer.diskStorage({destination:path.join(root,'public/uploads'),filename:(_q,f,cb)=>cb(null,Date.now()+'-'+f.originalname.replace(/[^\w.\-一-龥]/g,'_'))}),limits:{fileSize:50*1024*1024},fileFilter:(_q,f,cb)=>cb(null,/\.(pdf|docx?)$/i.test(f.originalname))});
router.post('/upload/image',upload.single('file'),(q,r)=>{if(!q.file)return r.status(400).json({ok:false,error:'仅支持 PNG/JPEG/WebP 图片'});r.status(201).json({ok:true,data:{url:'/uploads/'+q.file.filename}})});
router.post('/upload/document',documentUpload.single('file'),(q,r)=>{if(!q.file)return r.status(400).json({ok:false,error:'仅支持 PDF、DOC 或 DOCX 文件'});r.status(201).json({ok:true,data:{url:'/uploads/'+q.file.filename,name:q.file.originalname,type:q.file.mimetype,size:q.file.size}})});
router.post('/migrate/local',(q,r)=>{try{r.json({ok:true,data:{projectId:migrateLocal(q.body?.data||q.body||{})}})}catch(e){r.status(400).json({ok:false,error:e.message})}});
function sheetRows(sheet){return XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false});}
function headerIndex(rows,keys){return rows.findIndex(row=>keys.every(key=>row.some(cell=>String(cell).replace(/\s/g,'').includes(key))));}
function columnMap(header){const map={};header.forEach((v,i)=>{const s=String(v).replace(/\s|\n/g,'');if(/序号|No/i.test(s))map.seq=i;else if(/楼层|Floor/i.test(s))map.floor=i;else if(/门号|DoorNo/i.test(s))map.doorNumber=i;else if(/门型|Doortype/i.test(s))map.doorModel=i;else if(/房间|Room/i.test(s))map.roomFunction=i;else if(/宽度|DW/i.test(s))map.width=i;else if(/高度|DH/i.test(s))map.height=i;else if(/厚度|DT/i.test(s))map.thickness=i;else if(/樘数|数量|Qty/i.test(s))map.qty=i;else if(/门材质|材质|DM/i.test(s))map.material=i;else if(/开启|DoorOpening/i.test(s))map.doorType=i;else if(/五金组|HWSet|配置组/i.test(s))map.setCode=i;else if(/所属标段|区域|Area/i.test(s))map.section=i;else if(/备注|Notes/i.test(s))map.remark=i;});return map;}
router.post('/import/excel',importUpload.single('file'),(q,r)=>{if(!q.file)return r.status(400).json({ok:false,error:'缺少文件'});try{const result=importWorkbook(XLSX.readFile(q.file.path),Number(q.body?.projectId||0));r.json({ok:true,data:result})}catch(e){r.status(400).json({ok:false,error:e.message})}finally{fs.rmSync(q.file.path,{force:true})}});
router.get('/export/xlsx/template',(q,r)=>{const b=XLSX.utils.book_new(),rows=[['门表导入模板'],[],[],[],[],['序号','楼层','门号','门型号','房间位置描述','宽度','高度','门厚','樘数','门材质','门扇开启方式','五金组','所属标段','备注'],[1,'主楼1层','T1F1.1','ZFM2030乙','合用前室',2000,3000,'/',1,'金属防火门','双门','SET-03','1标段','']];XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet(rows),'门表');XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([['五金配置组别'],['组号','名称','产品型号','产品描述','表面处理','单位','单樘用量']]),'五金配置组别');XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([['五金产品清单'],['产品型号','产品名称','产品描述','表面处理','单位','价格']]),'五金产品清单');r.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('hardware-bom-template.xlsx').send(XLSX.write(b,{type:'buffer',bookType:'xlsx'}))});
router.get('/export/xlsx',(q,r)=>{const b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet(all('SELECT * FROM door_schedules WHERE project_id=?',[q.query.projectId||0])),'门表');XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet(all('SELECT * FROM hardware_sets')),'五金配置组别');XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet(all('SELECT * FROM hardware_set_items')),'五金组明细');XLSX.utils.book_append_sheet(b,XLSX.utils.json_to_sheet(all('SELECT * FROM products')),'五金产品清单');r.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('hardware-bom.xlsx').send(XLSX.write(b,{type:'buffer',bookType:'xlsx'}))});
module.exports=router;
